script/messages/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, ValidationError

# Message Form
class MessageForm(FlaskForm): 
    name = StringField('Name', validators=[DataRequired()])
    letter = TextAreaField('Message', validators=[DataRequired()]) 
    submit = SubmitField('Submit')

script/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

# New Post Form
class NewPostForm(FlaskForm): 
    title = StringField('Title', validators=[DataRequired()])
    # date = DateField('Date', default='%d/%m/%Y')
    content = TextAreaField('Content', validators=[DataRequired()]) 
    submit = SubmitField('Submit')

# Edit Post Form
class EditPostForm(FlaskForm): 
    title = StringField('Title', validators=[DataRequired()])
    content = StringField('Content', validators=[DataRequired()]) 
    submit = SubmitField('Make Changes')

script/messages/routes.py
from script import db
from script.models import  Message
from flask import render_template, url_for, flash, redirect, request, Blueprint
from script.messages.forms import MessageForm
from flask_login import login_required

messages = Blueprint('messages', __name__)

# Message form
@messages.route('/message', methods=['GET', 'POST'])
def message(): 
    form = MessageForm()
    # messages = Message.query.all()
    page = request.args.get('page', 1, type=int)
    messages = Message.query.order_by(Message.date.desc()).paginate(page=page, per_page=20)
    if form.validate_on_submit():
        message = Message(name=form.name.data, letter=form.letter.data)
        db.session.add(message)
        db.session.commit()
        flash('Your message has been posted!', 'success')
        return redirect(url_for('messages.message'))
    return render_template('message.html', title='Message Board', form=form, posts=messages)

# Delete message
# @app.route("/message/<int:message_id>")
# def onemessage(message_id):
#     message = Message.query.get_or_404(message_id)
#     return render_template('onemessage.html', post=message)

@messages.route("/message/<int:message_id>/delete", methods=['POST']) 
@login_required
def delete_message(message_id):
    message = Message.query.get_or_404(message_id) 
    db.session.delete(message)
    db.session.commit()
    flash('Message has been deleted!', 'success') 
    
    return redirect(url_for('messages.message'))

script/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from script.models import Post
from script import db
from script.posts.forms import NewPostForm, EditPostForm
from flask_login import current_user, login_required

posts = Blueprint('posts', __name__)

#New post
@posts.route('/newpost', methods=['GET', 'POST'])
@login_required
def newpost(): 
    form = NewPostForm()
    if form.validate_on_submit():
        # Add new post to database
        post = Post(title=form.title.data, content=form.content.data, user_id=current_user.id)
        db.session.add(post)
        db.session.commit()

        flash('New poem posted', 'success')
        return redirect(url_for('main.home'))
    return render_template('newpoem.html', title='New Post', form=form, legend='New Post')

# Update Post
@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
# Checking entered data (current user) against database using query
def updatepost(post_id):

    form = NewPostForm()

    post = Post.query.get_or_404(post_id)
    # make sure only author can edit
    if post.author != current_user:
    # 403 - forbidden route
        abort(403)

    # validate and update
    if form.validate_on_submit(): 
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))

    # automatically fill in current username/email in fields
    elif request.method == 'GET': 
        form.title.data = post.title
        form.content.data = post.content

    return render_template('newpoem.html', title='Update Post', form=form, legend='Update Post')

# Individual posts
@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)

# Index of post titles
@posts.route("/titles")
def titles():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.title.asc()).paginate(page=page, per_page=100)
    return render_template('titles.html', title='Index', posts=posts)

# Delete posts
@posts.route("/post/<int:post_id>/delete", methods=['POST']) 
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id) 
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success') 
    
    return redirect(url_for('main.home'))

script/users/routes.py
from script import db, bcrypt
from script.models import User
from flask import render_template, url_for, flash, redirect, request, Blueprint
from script.users.forms import LoginForm, RegisterForm
from flask_login import login_user, current_user, logout_user, login_required

users = Blueprint('users', __name__)

# Register
@users.route('/boomboomba', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegisterForm()
    if form.validate_on_submit():

        # Hash password
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        # Add user info into database
        user = User(email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()

        flash(f'Account created for {form.email.data}!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

# Login
@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated: 
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        # Check entered data form.email.data against database using query
        user = User.query.filter_by(email=form.email.data).first()

        # if user exists and password matches database
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            # log in
            login_user(user)
            # if previous page exists that redirects user to log in page
            # redirect user back to that page
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))

            flash('You are now logged in', 'success')
            return redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Log In', form=form)

# Logout
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))
    # we already know which user it is return redirect(url_for('home'))

script/templates/about.html
{% extends "layout.html" %}
{% block content %}

    <div class="about">
        <img src="{{ url_for('static', filename='img/icon.jpg') }}" alt="icon">
        <div class="description">
            <h3>"Small, cute, brave and immature"</h3><br>
            <p class="quote"> - No Work Club et al. (2020)</p><br>
            <p>Who is Steve? He is a weird old punk, mohawk blondie, wild guitarist, badass biker, 
                sketchy veggie, human hater, Noodle Bar loyal fan, 'World Class Facility' permanent inhabitant.
                Steve is many things, but at the age of 51 he has uncovered another one of his many identities - 
                A poet. He has since written dozens of beautiful poems that are currently published in this blog.
                Enjoy your little adventure with Steve and don't forget to leave a lovely message to him on the message board!</p><br>
            <p>P.S. Hover over Steve and watch him dance!</p>
        </div>
    </div>

{% endblock content %}

script/templates/index.html
{% extends "layout.html" %}

{% block content %}

    <!-- Poems -->
    <main>
        <article>
            {% for post in posts.items %}
                <div class="post-content">
                    <h2><a href="{{ url_for('posts.post', post_id=post.id) }}">{{post.title}}</a></h2>
                    <br>
                    <p class="date">{{post.date.strftime('%B %d, %Y')}}</p>
                    <br>
                    <p class="poem">{{post.content}}</p>
                </div>
            {% endfor %}

            <div class="pagination">
                {% for page_num in posts.iter_pages(left_edge=2, right_edge=2, left_current=1, right_current=2) %} 
                    {% if page_num %}
                        {% if posts.page == page_num %}
                            <a class="btn btn-info mb-4 btn-md page" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a> 
                        {% else %}
                            <a class="btn btn-outline-info mb-4 btn-md page" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
                        {% endif %}
                    {% else %}
                        ...
                    {% endif %} 
                {% endfor %}
            </div>
        </article>
    </main>

{% endblock content %}

script/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

        <link rel="icon" href="{{ url_for('static', filename='img/mohawk.png') }}">
        {% if title %}
            <title>Garner Edge Poetry - {{ title }}</title>
        {% else %}
            <title>Garner Edge Poetry</title>
        {% endif %}
    </head>
    <body>

        <!-- Nav Bar -->
        <div class="header">
            <nav>
                <a class="hamburger" href=""></a>
                <ul class="links">
                    <li><a href="/" class="home-icon">Home</a></li>
                    <div class="nested-nav">
                        <li><a href="/about">About</a></li>
                        <li><a href="/titles">Index</a></li>
                        <li><a href="/message">Message</a></li>
                    </div>
                </ul>
            </nav>

        </div>

        <!-- Banner -->
        <section class="banner">
            <img src="{{ url_for('static', filename='img/Banner_final.png') }}" alt="banner"> 
        </section>

        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} flash">{{ message }}</div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        {% block content %}{% endblock %}

        <!-- ***from bootstrap website*** -->
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>

    <div class ="footer">

        <span class="foot">
            <!-- If user is logged in -->
            {% if current_user.is_authenticated %}
                <a href="{{ url_for('posts.newpost') }}">New Post</a>
                <a href="{{ url_for('users.logout') }}">Log Out</a> 
            {% else %}
                <a href="{{ url_for('users.login') }}">Log In</a>
            {% endif %}
        </span>

    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{{ url_for('static', filename='menu.js') }}"></script>
</html>

script/templates/login.html
{% extends "layout.html" %}
{% block content %}

        <div class="login-container">
            <h4>Log In</h4>
            <form class="login-form" method="POST" action="">
                {{ form.csrf_token }}

                <div class="form-field">
                    {{ form.email.label }}
                    {{ form.email }}

                    {% if form.email.errors %}
                        <div class="errors">
                            {% for error in form.email.errors %}
                                <p style="text-align: center; color: rgb(241, 82, 82); font-size: 0.8em;">{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="form-field">
                    {{ form.password.label }}
                    {{ form.password }}

                    {% if form.password.errors %}
                        <div class="errors">
                            {% for error in form.password.errors %}
                                <p style="text-align: center; color: rgb(241, 82, 82); font-size: 0.8em;">{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                
                <br>
                {{ form.submit(class="boom") }}
            </form>
        </div>

{% endblock content %}

script/templates/message.html
{% extends "layout.html" %}
{% block content %}

    <div class="message-container">

        <!-- <div class="form-container">
            <h4>Send a message to Steve</h4>
            <form class="message-form" method="POST" action="">
                <label for="name">Name</label>
                <input type="text" name="name" id="name" required>
                <label for="message">Message</label>
                <div class="text-container">
                    <textarea type="text" name="message" id="message" required></textarea>
                </div>
                <input type="submit" value="Submit">
            </form>
        </div> -->

        <div class="form-container">
            <h4>Send a message to Steve</h4>
            <form class="message-form" method="POST" action="">
                {{ form.hidden_tag() }}
                
                <div class="form-field">
                    {{ form.name.label }}
                    {{ form.name }}
                    {% if form.name.errors %}
                        <div class="errors">
                            {% for error in form.name.errors %}
                                <p style="text-align: center; color: rgb(241, 82, 82); font-size: 0.8em;">{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="form-field">
                    {{ form.letter.label }}
                    <div class="text-container">
                        {{  form.letter }}
                    </div>
                    {% if form.letter.errors %}
                        <div class="errors">
                            {% for error in form.letter.errors %}
                                <p style="text-align: center; color: rgb(241, 82, 82); font-size: 0.8em;">{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                {{ form.submit(class="boom") }}
            </form>
        </div>

        <div class="received-container">
            <h4>Message Board</h4>
            {% for message in posts.items %}
                <div class="received">

                    {% if current_user.is_authenticated %}
                        <div class="top-message">
                            <p class="name">{{ message.name }}</p>
                            <button type="button" class="btn btn-xs btn-outline-dark" data-toggle="modal" data-target="#deleteModal">
                                <i class="material-icons w3-large">delete</i>
                            </button>
                        </div>
                        <p class="date">{{ message.date.strftime('%B %d, %Y %H:%M') }}</p>
                    {% else %}
                    <div class="top-message">
                        <p class="name">{{ message.name }}</p>
                        <p class="date">{{ message.date.strftime('%B %d, %Y %H:%M') }}</p>
                    </div>
                        {% endif %}

                    <p class="message">{{ message.letter }}</p>
                </div>

                <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document"> 
                        <div class="modal-content">
                            <div class="modal-header">
                                    <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span> 
                                </button>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <form action="{{ url_for('messages.delete_message', message_id = message.id) }}" method="POST">
                                    <input class ="btn btn-danger" type="submit" value="Delete"> 
                                </form>
                            </div> 
                        </div>
                    </div> 
                </div>
            {% endfor %}
        </div>

        <div class="pagination">
            {% for page_num in posts.iter_pages(left_edge=2, right_edge=2, left_current=1, right_current=2) %} 
                {% if page_num %}
                    {% if posts.page == page_num %}
                        <a class="btn btn-info mb-4 btn-md page" href="{{ url_for('messages.message', page=page_num) }}">{{ page_num }}</a> 
                    {% else %}
                        <a class="btn btn-outline-info mb-4 btn-md page" href="{{ url_for('messages.message', page=page_num) }}">{{ page_num }}</a>
                    {% endif %}
                {% else %}
                    ...
                {% endif %} 
            {% endfor %}
        </div>

    </div>


{% endblock content %}

script/templates/newpoem.html
{% extends "layout.html" %}
{% block content %}

    <div class="newpost-container">
        <div class="form-container">
            <h4>{{ legend }}</h4>

            <form class="message-form" method="POST" action="">
                {{ form.hidden_tag() }}

                <div class="form-field">
                    {{ form.title.label }}
                    {{ form.title }}
                    {% if form.title.errors %}
                        <div class="errors">
                            {% for error in form.title.errors %}
                                <p style="text-align: center; color: rgb(241, 82, 82); font-size: 0.8em;">{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="form-field">
                    {{ form.content.label }}
                    <div class="text-container">
                        {{  form.content }}
                    </div>
                    {% if form.content.errors %}
                        <div class="errors">
                            {% for error in form.content.errors %}
                                <p style="text-align: center; color: rgb(241, 82, 82); font-size: 0.8em;">{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                {{  form.submit(class="boom") }}
            </form>
        </div>
    </div>

{% endblock content %}

script/templates/onemessage.html
{% extends "layout.html" %}
{% block content %}

        <div class="message-container">
            <div class="received-container">
                <div class="received">
                    <div class="top-message">
                        <p class="name">{{ post.name }}</p>
                        <button type="button" class="btn" data-toggle="modal" data-target="#deleteModal">
                            <i class="material-icons">delete</i>
                        </button>
                    </div>
                    <p class="message">{{ post.letter }}</p>
                </div>
            </div>
        </div>
    
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document"> 
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span> 
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <form action="{{ url_for('messages.delete_message', message_id = post.id) }}" method="POST">
                        <input class ="btn btn-danger" type="submit" value="Delete"> 
                    </form>
                </div> 
            </div>
        </div> 
    </div>

{% endblock content %}

script/templates/post.html
{% extends "layout.html" %}

{% block content %}

    <!-- Poems -->
    <main>
        <article>
            <div class="poem">
                <h2>{{ post.title }}</h2>
                <div class="content">
                    <p class="date">{{ post.date.strftime('%B %d, %Y') }}</p>
                    <p class="poem">{{ post.content }}</p>
                    {% if current_user.is_authenticated %}
                    <div class="post-tool">
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.updatepost', post_id=post.id) }}">Edit</a>
                        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>    
                    </div>
                    {% endif %}
                </div>
            </div>
        </article>
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document"> 
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                        <button type="button" class="close" data-dismiss="modal" aria- label="Close">
                            <span aria-hidden="true">&times;</span> 
                        </button>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                            <input class ="btn btn-danger" type="submit" value="Delete"> 
                        </form>
                    </div> 
                </div>
            </div> 
        </div>
    </main>

{% endblock content %}

script/templates/register.html
{% extends "layout.html" %}
{% block content %}

    <div class="login-container">
        <h4>Register</h4>
        <form class="login-form" method="POST" action="">

            {{ form.hidden_tag() }}

            <div class="form-field">
                {{ form.email.label }}
                {{ form.email }}

                {% if form.email.errors %}
                    <div class="errors">
                        {% for error in form.email.errors %}
                            <p style="text-align: center; color: rgb(241, 82, 82); font-size: 0.8em;">{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <div class="form-field">
                {{ form.password.label }}
                {{ form.password }}

                {% if form.password.errors %}
                    <div class="errors">
                        {% for error in form.password.errors %}
                            <p style="text-align: center; color: rgb(241, 82, 82); font-size: 0.8em;">{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <div class="form-field">
                {{ form.confirm.label }}
                {{ form.confirm }}

                {% if form.confirm.errors %}
                    <div class="errors">
                        {% for error in form.confirm.errors %}
                            <p style="text-align: center; color: rgb(241, 82, 82); font-size: 0.8em;">Password does not match.</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <br>
            {{ form.submit(class="boom") }}
        </form>
    </div>

{% endblock content %}

script/templates/titles.html
{% extends "layout.html" %}
{% block content %}

    <div class="message-container">
        <h4>Index</h4>
        {% for post in posts.items %}
            <a class="title" href="{{ url_for('posts.post', post_id=post.id)}}">{{ post.title }}</a>
        {% endfor %}
    </div>  

{% endblock content %}